-- MySQL Script generated by MySQL Workbench
-- Tue Apr 20 16:10:47 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema groupproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema groupproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `groupproject` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `StudentID` INT NOT NULL,
  `StudentName` VARCHAR(45) NULL,
  `StudentEmail` VARCHAR(45) NULL,
  `StudentPassword` VARCHAR(45) NULL,
  PRIMARY KEY (`StudentID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `ProfessorID` VARCHAR(45) NOT NULL,
  `ProfessorName` VARCHAR(45) NULL,
  PRIMARY KEY (`ProfessorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `CourseID` INT NOT NULL,
  `CourseName` VARCHAR(45) NULL,
  `ProfessorID` INT NULL,
  PRIMARY KEY (`CourseID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evaluation` (
  `EvaluationID` INT NOT NULL,
  `StudentID` INT NULL,
  `EvaluatedStudentsID` VARCHAR(45) NULL,
  `EvalQuestions` VARCHAR(45) NULL,
  `GroupNumber` INT NULL,
  `CourseID` INT NULL,
  PRIMARY KEY (`EvaluationID`),
  INDEX `fk_Evaluation_Student1_idx` (`StudentID` ASC) VISIBLE,
  INDEX `fk_Evaluation_Course1_idx` (`CourseID` ASC) VISIBLE,
  CONSTRAINT `fk_Evaluation_Student1`
    FOREIGN KEY (`StudentID`)
    REFERENCES `mydb`.`Student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evaluation_Course1`
    FOREIGN KEY (`CourseID`)
    REFERENCES `mydb`.`Course` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Group` (
  `GroupNumber` INT NOT NULL,
  `StudentIDList` VARCHAR(45) NULL,
  `ProfessorID` VARCHAR(45) NULL,
  `CourseID` INT NULL,
  PRIMARY KEY (`GroupNumber`),
  INDEX `fk_Group_Course1_idx` (`CourseID` ASC) VISIBLE,
  INDEX `fk_Group_Professor1_idx` (`ProfessorID` ASC) VISIBLE,
  CONSTRAINT `fk_Group_Course1`
    FOREIGN KEY (`CourseID`)
    REFERENCES `mydb`.`Course` (`CourseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Group_Professor1`
    FOREIGN KEY (`ProfessorID`)
    REFERENCES `mydb`.`Professor` (`ProfessorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `groupproject` ;

-- -----------------------------------------------------
-- Table `groupproject`.`program_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupproject`.`program_info` (
  `program_id` INT NOT NULL,
  `program_name` VARCHAR(50) NOT NULL,
  `total_credits` INT NOT NULL,
  `num_core_courses` INT NULL DEFAULT NULL,
  `salary_postgrad` INT NULL DEFAULT NULL,
  `electives_offered` TINYINT NULL DEFAULT NULL,
  `class_size` INT NULL DEFAULT NULL,
  `avg_yrs_exp` DECIMAL(4,2) NULL DEFAULT NULL,
  PRIMARY KEY (`program_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `groupproject`.`application_deadlines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupproject`.`application_deadlines` (
  `app_id` INT NOT NULL,
  `deadline` VARCHAR(45) NULL DEFAULT NULL,
  `deadline_details` VARCHAR(150) NULL DEFAULT NULL,
  `program_info_program_id` INT NOT NULL,
  PRIMARY KEY (`app_id`),
  INDEX `fk_application_deadlines_program_info1_idx` (`program_info_program_id` ASC) VISIBLE,
  CONSTRAINT `fk_application_deadlines_program_info1`
    FOREIGN KEY (`program_info_program_id`)
    REFERENCES `groupproject`.`program_info` (`program_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `groupproject`.`core_course_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupproject`.`core_course_info` (
  `course_id` INT NOT NULL,
  `course_name` VARCHAR(150) NULL DEFAULT NULL,
  `course_tag` VARCHAR(45) NULL DEFAULT NULL,
  `credits` INT NULL DEFAULT NULL,
  `course_description` VARCHAR(2000) NULL DEFAULT NULL,
  `syllabus_description` VARCHAR(1500) NULL DEFAULT NULL,
  `syllabus_url` VARCHAR(500) NULL DEFAULT NULL,
  `program_info_program_id` INT NOT NULL,
  PRIMARY KEY (`course_id`),
  INDEX `fk_core_course_info_program_info1_idx` (`program_info_program_id` ASC) VISIBLE,
  CONSTRAINT `fk_core_course_info_program_info1`
    FOREIGN KEY (`program_info_program_id`)
    REFERENCES `groupproject`.`program_info` (`program_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `groupproject`.`professor_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupproject`.`professor_info` (
  `professor_id` INT NOT NULL,
  `professor_firstname` VARCHAR(25) NULL DEFAULT NULL,
  `professor_lastname` VARCHAR(25) NULL DEFAULT NULL,
  `professor_ranking` INT NULL DEFAULT NULL,
  `program_info_program_id` INT NOT NULL,
  PRIMARY KEY (`professor_id`),
  INDEX `fk_professor_info_program_info1_idx` (`program_info_program_id` ASC) VISIBLE,
  CONSTRAINT `fk_professor_info_program_info1`
    FOREIGN KEY (`program_info_program_id`)
    REFERENCES `groupproject`.`program_info` (`program_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `groupproject`.`core_course_schd`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupproject`.`core_course_schd` (
  `table_id` INT NOT NULL,
  `semester` ENUM('Fall', 'Spring', 'Summer', 'Winter', 'Unknown') NOT NULL,
  `professor_info_professor_id` INT NULL DEFAULT NULL,
  `core_course_info_course_id` INT NOT NULL,
  `program_info_program_id` INT NOT NULL,
  PRIMARY KEY (`table_id`),
  INDEX `fk_core_course_schd_professor_info_idx` (`professor_info_professor_id` ASC) VISIBLE,
  INDEX `fk_core_course_schd_program_info1_idx` (`program_info_program_id` ASC) VISIBLE,
  INDEX `fk_core_course_schd_core_course_info1_idx` (`core_course_info_course_id` ASC) VISIBLE,
  CONSTRAINT `fk_core_course_schd_core_course_info1`
    FOREIGN KEY (`core_course_info_course_id`)
    REFERENCES `groupproject`.`core_course_info` (`course_id`),
  CONSTRAINT `fk_core_course_schd_professor_info`
    FOREIGN KEY (`professor_info_professor_id`)
    REFERENCES `groupproject`.`professor_info` (`professor_id`),
  CONSTRAINT `fk_core_course_schd_program_info1`
    FOREIGN KEY (`program_info_program_id`)
    REFERENCES `groupproject`.`program_info` (`program_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `groupproject`.`ranking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupproject`.`ranking` (
  `ranking_id` INT NOT NULL,
  `rankingOrg` VARCHAR(75) NULL DEFAULT NULL,
  `rankingCategory` VARCHAR(75) NULL DEFAULT NULL,
  `rank` INT NULL DEFAULT NULL,
  `program_info_program_id` INT NOT NULL,
  PRIMARY KEY (`ranking_id`),
  INDEX `fk_ranking_program_info1_idx` (`program_info_program_id` ASC) VISIBLE,
  CONSTRAINT `fk_ranking_program_info1`
    FOREIGN KEY (`program_info_program_id`)
    REFERENCES `groupproject`.`program_info` (`program_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `groupproject`.`tuition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupproject`.`tuition` (
  `residency` VARCHAR(45) NOT NULL,
  `cost_per_credit` DECIMAL(7,2) NULL DEFAULT NULL,
  `program_info_program_id` INT NOT NULL,
  PRIMARY KEY (`residency`, `program_info_program_id`),
  INDEX `fk_tuition_program_info1_idx` (`program_info_program_id` ASC) VISIBLE,
  CONSTRAINT `fk_tuition_program_info1`
    FOREIGN KEY (`program_info_program_id`)
    REFERENCES `groupproject`.`program_info` (`program_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
